backend:
  name: github
  repo: evanxd/eleventy-duo

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post.template"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
